# Generated by Django 2.2.1 on 2019-08-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_tet',
            new_name='choice_text',
        ),
    ]
